apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-html-1
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-index-html-1
        configMap:
          name: nginx-index-html-1
      - name: nginx-config
        configMap:
          name: nginx-index-html-1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Nginx 1</h1>
    </body>
    </html>
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /nginx1 { 
            alias /usr/share/nginx/html/;
            index index.html;
        }
    }