apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  selector:
    matchLabels:
      run: nginx-2
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index-html-2
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-config    # nginx.conf를 마운트하기 위한 볼륨 마운트 추가
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-index-html-2
        configMap:
          name: nginx-index-html-2
      - name: nginx-config     # nginx.conf를 위한 볼륨 추가
        configMap:
          name: nginx-index-html-2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  labels:
    run: nginx-2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html-2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Nginx 2</h1>
    </body>
    </html>
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /nginx2 {
            alias /usr/share/nginx/html/;
            index index.html;
        }
    }